#!/usr/bin/env php
<?php
// application.php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use MikeBell\GhostToSculpin;

$application = new Application();
$application->add(new GhostToSculpin\Migrate());
$application->run();